# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ijaehyeon/source/42_printf

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ijaehyeon/source/42_printf

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /Users/ijaehyeon/source/42_printf && $(CMAKE_COMMAND) -E cmake_progress_start /Users/ijaehyeon/source/42_printf/CMakeFiles /Users/ijaehyeon/source/42_printf/libft//CMakeFiles/progress.marks
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libft/all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ijaehyeon/source/42_printf/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libft/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libft/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libft/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /Users/ijaehyeon/source/42_printf && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
libft/CMakeFiles/libft.dir/rule:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libft/CMakeFiles/libft.dir/rule
.PHONY : libft/CMakeFiles/libft.dir/rule

# Convenience name for target.
libft: libft/CMakeFiles/libft.dir/rule
.PHONY : libft

# fast build rule for target.
libft/fast:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/build
.PHONY : libft/fast

ft_atoi.o: ft_atoi.c.o
.PHONY : ft_atoi.o

# target to build an object file
ft_atoi.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_atoi.c.o
.PHONY : ft_atoi.c.o

ft_atoi.i: ft_atoi.c.i
.PHONY : ft_atoi.i

# target to preprocess a source file
ft_atoi.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_atoi.c.i
.PHONY : ft_atoi.c.i

ft_atoi.s: ft_atoi.c.s
.PHONY : ft_atoi.s

# target to generate assembly for a file
ft_atoi.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_atoi.c.s
.PHONY : ft_atoi.c.s

ft_bzero.o: ft_bzero.c.o
.PHONY : ft_bzero.o

# target to build an object file
ft_bzero.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_bzero.c.o
.PHONY : ft_bzero.c.o

ft_bzero.i: ft_bzero.c.i
.PHONY : ft_bzero.i

# target to preprocess a source file
ft_bzero.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_bzero.c.i
.PHONY : ft_bzero.c.i

ft_bzero.s: ft_bzero.c.s
.PHONY : ft_bzero.s

# target to generate assembly for a file
ft_bzero.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_bzero.c.s
.PHONY : ft_bzero.c.s

ft_calloc.o: ft_calloc.c.o
.PHONY : ft_calloc.o

# target to build an object file
ft_calloc.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_calloc.c.o
.PHONY : ft_calloc.c.o

ft_calloc.i: ft_calloc.c.i
.PHONY : ft_calloc.i

# target to preprocess a source file
ft_calloc.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_calloc.c.i
.PHONY : ft_calloc.c.i

ft_calloc.s: ft_calloc.c.s
.PHONY : ft_calloc.s

# target to generate assembly for a file
ft_calloc.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_calloc.c.s
.PHONY : ft_calloc.c.s

ft_isalnum.o: ft_isalnum.c.o
.PHONY : ft_isalnum.o

# target to build an object file
ft_isalnum.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_isalnum.c.o
.PHONY : ft_isalnum.c.o

ft_isalnum.i: ft_isalnum.c.i
.PHONY : ft_isalnum.i

# target to preprocess a source file
ft_isalnum.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_isalnum.c.i
.PHONY : ft_isalnum.c.i

ft_isalnum.s: ft_isalnum.c.s
.PHONY : ft_isalnum.s

# target to generate assembly for a file
ft_isalnum.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_isalnum.c.s
.PHONY : ft_isalnum.c.s

ft_isalpha.o: ft_isalpha.c.o
.PHONY : ft_isalpha.o

# target to build an object file
ft_isalpha.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_isalpha.c.o
.PHONY : ft_isalpha.c.o

ft_isalpha.i: ft_isalpha.c.i
.PHONY : ft_isalpha.i

# target to preprocess a source file
ft_isalpha.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_isalpha.c.i
.PHONY : ft_isalpha.c.i

ft_isalpha.s: ft_isalpha.c.s
.PHONY : ft_isalpha.s

# target to generate assembly for a file
ft_isalpha.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_isalpha.c.s
.PHONY : ft_isalpha.c.s

ft_isascii.o: ft_isascii.c.o
.PHONY : ft_isascii.o

# target to build an object file
ft_isascii.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_isascii.c.o
.PHONY : ft_isascii.c.o

ft_isascii.i: ft_isascii.c.i
.PHONY : ft_isascii.i

# target to preprocess a source file
ft_isascii.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_isascii.c.i
.PHONY : ft_isascii.c.i

ft_isascii.s: ft_isascii.c.s
.PHONY : ft_isascii.s

# target to generate assembly for a file
ft_isascii.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_isascii.c.s
.PHONY : ft_isascii.c.s

ft_isdigit.o: ft_isdigit.c.o
.PHONY : ft_isdigit.o

# target to build an object file
ft_isdigit.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_isdigit.c.o
.PHONY : ft_isdigit.c.o

ft_isdigit.i: ft_isdigit.c.i
.PHONY : ft_isdigit.i

# target to preprocess a source file
ft_isdigit.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_isdigit.c.i
.PHONY : ft_isdigit.c.i

ft_isdigit.s: ft_isdigit.c.s
.PHONY : ft_isdigit.s

# target to generate assembly for a file
ft_isdigit.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_isdigit.c.s
.PHONY : ft_isdigit.c.s

ft_isprint.o: ft_isprint.c.o
.PHONY : ft_isprint.o

# target to build an object file
ft_isprint.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_isprint.c.o
.PHONY : ft_isprint.c.o

ft_isprint.i: ft_isprint.c.i
.PHONY : ft_isprint.i

# target to preprocess a source file
ft_isprint.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_isprint.c.i
.PHONY : ft_isprint.c.i

ft_isprint.s: ft_isprint.c.s
.PHONY : ft_isprint.s

# target to generate assembly for a file
ft_isprint.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_isprint.c.s
.PHONY : ft_isprint.c.s

ft_lstadd_back.o: ft_lstadd_back.c.o
.PHONY : ft_lstadd_back.o

# target to build an object file
ft_lstadd_back.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstadd_back.c.o
.PHONY : ft_lstadd_back.c.o

ft_lstadd_back.i: ft_lstadd_back.c.i
.PHONY : ft_lstadd_back.i

# target to preprocess a source file
ft_lstadd_back.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstadd_back.c.i
.PHONY : ft_lstadd_back.c.i

ft_lstadd_back.s: ft_lstadd_back.c.s
.PHONY : ft_lstadd_back.s

# target to generate assembly for a file
ft_lstadd_back.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstadd_back.c.s
.PHONY : ft_lstadd_back.c.s

ft_lstadd_front.o: ft_lstadd_front.c.o
.PHONY : ft_lstadd_front.o

# target to build an object file
ft_lstadd_front.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstadd_front.c.o
.PHONY : ft_lstadd_front.c.o

ft_lstadd_front.i: ft_lstadd_front.c.i
.PHONY : ft_lstadd_front.i

# target to preprocess a source file
ft_lstadd_front.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstadd_front.c.i
.PHONY : ft_lstadd_front.c.i

ft_lstadd_front.s: ft_lstadd_front.c.s
.PHONY : ft_lstadd_front.s

# target to generate assembly for a file
ft_lstadd_front.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstadd_front.c.s
.PHONY : ft_lstadd_front.c.s

ft_lstclear.o: ft_lstclear.c.o
.PHONY : ft_lstclear.o

# target to build an object file
ft_lstclear.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstclear.c.o
.PHONY : ft_lstclear.c.o

ft_lstclear.i: ft_lstclear.c.i
.PHONY : ft_lstclear.i

# target to preprocess a source file
ft_lstclear.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstclear.c.i
.PHONY : ft_lstclear.c.i

ft_lstclear.s: ft_lstclear.c.s
.PHONY : ft_lstclear.s

# target to generate assembly for a file
ft_lstclear.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstclear.c.s
.PHONY : ft_lstclear.c.s

ft_lstdelone.o: ft_lstdelone.c.o
.PHONY : ft_lstdelone.o

# target to build an object file
ft_lstdelone.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstdelone.c.o
.PHONY : ft_lstdelone.c.o

ft_lstdelone.i: ft_lstdelone.c.i
.PHONY : ft_lstdelone.i

# target to preprocess a source file
ft_lstdelone.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstdelone.c.i
.PHONY : ft_lstdelone.c.i

ft_lstdelone.s: ft_lstdelone.c.s
.PHONY : ft_lstdelone.s

# target to generate assembly for a file
ft_lstdelone.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstdelone.c.s
.PHONY : ft_lstdelone.c.s

ft_lstiter.o: ft_lstiter.c.o
.PHONY : ft_lstiter.o

# target to build an object file
ft_lstiter.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstiter.c.o
.PHONY : ft_lstiter.c.o

ft_lstiter.i: ft_lstiter.c.i
.PHONY : ft_lstiter.i

# target to preprocess a source file
ft_lstiter.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstiter.c.i
.PHONY : ft_lstiter.c.i

ft_lstiter.s: ft_lstiter.c.s
.PHONY : ft_lstiter.s

# target to generate assembly for a file
ft_lstiter.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstiter.c.s
.PHONY : ft_lstiter.c.s

ft_lstlast.o: ft_lstlast.c.o
.PHONY : ft_lstlast.o

# target to build an object file
ft_lstlast.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstlast.c.o
.PHONY : ft_lstlast.c.o

ft_lstlast.i: ft_lstlast.c.i
.PHONY : ft_lstlast.i

# target to preprocess a source file
ft_lstlast.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstlast.c.i
.PHONY : ft_lstlast.c.i

ft_lstlast.s: ft_lstlast.c.s
.PHONY : ft_lstlast.s

# target to generate assembly for a file
ft_lstlast.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstlast.c.s
.PHONY : ft_lstlast.c.s

ft_lstmap.o: ft_lstmap.c.o
.PHONY : ft_lstmap.o

# target to build an object file
ft_lstmap.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstmap.c.o
.PHONY : ft_lstmap.c.o

ft_lstmap.i: ft_lstmap.c.i
.PHONY : ft_lstmap.i

# target to preprocess a source file
ft_lstmap.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstmap.c.i
.PHONY : ft_lstmap.c.i

ft_lstmap.s: ft_lstmap.c.s
.PHONY : ft_lstmap.s

# target to generate assembly for a file
ft_lstmap.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstmap.c.s
.PHONY : ft_lstmap.c.s

ft_lstnew.o: ft_lstnew.c.o
.PHONY : ft_lstnew.o

# target to build an object file
ft_lstnew.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstnew.c.o
.PHONY : ft_lstnew.c.o

ft_lstnew.i: ft_lstnew.c.i
.PHONY : ft_lstnew.i

# target to preprocess a source file
ft_lstnew.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstnew.c.i
.PHONY : ft_lstnew.c.i

ft_lstnew.s: ft_lstnew.c.s
.PHONY : ft_lstnew.s

# target to generate assembly for a file
ft_lstnew.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstnew.c.s
.PHONY : ft_lstnew.c.s

ft_lstsize.o: ft_lstsize.c.o
.PHONY : ft_lstsize.o

# target to build an object file
ft_lstsize.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstsize.c.o
.PHONY : ft_lstsize.c.o

ft_lstsize.i: ft_lstsize.c.i
.PHONY : ft_lstsize.i

# target to preprocess a source file
ft_lstsize.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstsize.c.i
.PHONY : ft_lstsize.c.i

ft_lstsize.s: ft_lstsize.c.s
.PHONY : ft_lstsize.s

# target to generate assembly for a file
ft_lstsize.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_lstsize.c.s
.PHONY : ft_lstsize.c.s

ft_memchr.o: ft_memchr.c.o
.PHONY : ft_memchr.o

# target to build an object file
ft_memchr.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_memchr.c.o
.PHONY : ft_memchr.c.o

ft_memchr.i: ft_memchr.c.i
.PHONY : ft_memchr.i

# target to preprocess a source file
ft_memchr.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_memchr.c.i
.PHONY : ft_memchr.c.i

ft_memchr.s: ft_memchr.c.s
.PHONY : ft_memchr.s

# target to generate assembly for a file
ft_memchr.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_memchr.c.s
.PHONY : ft_memchr.c.s

ft_memcmp.o: ft_memcmp.c.o
.PHONY : ft_memcmp.o

# target to build an object file
ft_memcmp.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_memcmp.c.o
.PHONY : ft_memcmp.c.o

ft_memcmp.i: ft_memcmp.c.i
.PHONY : ft_memcmp.i

# target to preprocess a source file
ft_memcmp.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_memcmp.c.i
.PHONY : ft_memcmp.c.i

ft_memcmp.s: ft_memcmp.c.s
.PHONY : ft_memcmp.s

# target to generate assembly for a file
ft_memcmp.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_memcmp.c.s
.PHONY : ft_memcmp.c.s

ft_memcpy.o: ft_memcpy.c.o
.PHONY : ft_memcpy.o

# target to build an object file
ft_memcpy.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_memcpy.c.o
.PHONY : ft_memcpy.c.o

ft_memcpy.i: ft_memcpy.c.i
.PHONY : ft_memcpy.i

# target to preprocess a source file
ft_memcpy.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_memcpy.c.i
.PHONY : ft_memcpy.c.i

ft_memcpy.s: ft_memcpy.c.s
.PHONY : ft_memcpy.s

# target to generate assembly for a file
ft_memcpy.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_memcpy.c.s
.PHONY : ft_memcpy.c.s

ft_memmove.o: ft_memmove.c.o
.PHONY : ft_memmove.o

# target to build an object file
ft_memmove.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_memmove.c.o
.PHONY : ft_memmove.c.o

ft_memmove.i: ft_memmove.c.i
.PHONY : ft_memmove.i

# target to preprocess a source file
ft_memmove.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_memmove.c.i
.PHONY : ft_memmove.c.i

ft_memmove.s: ft_memmove.c.s
.PHONY : ft_memmove.s

# target to generate assembly for a file
ft_memmove.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_memmove.c.s
.PHONY : ft_memmove.c.s

ft_memset.o: ft_memset.c.o
.PHONY : ft_memset.o

# target to build an object file
ft_memset.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_memset.c.o
.PHONY : ft_memset.c.o

ft_memset.i: ft_memset.c.i
.PHONY : ft_memset.i

# target to preprocess a source file
ft_memset.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_memset.c.i
.PHONY : ft_memset.c.i

ft_memset.s: ft_memset.c.s
.PHONY : ft_memset.s

# target to generate assembly for a file
ft_memset.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_memset.c.s
.PHONY : ft_memset.c.s

ft_putchar_fd.o: ft_putchar_fd.c.o
.PHONY : ft_putchar_fd.o

# target to build an object file
ft_putchar_fd.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_putchar_fd.c.o
.PHONY : ft_putchar_fd.c.o

ft_putchar_fd.i: ft_putchar_fd.c.i
.PHONY : ft_putchar_fd.i

# target to preprocess a source file
ft_putchar_fd.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_putchar_fd.c.i
.PHONY : ft_putchar_fd.c.i

ft_putchar_fd.s: ft_putchar_fd.c.s
.PHONY : ft_putchar_fd.s

# target to generate assembly for a file
ft_putchar_fd.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_putchar_fd.c.s
.PHONY : ft_putchar_fd.c.s

ft_putendl_fd.o: ft_putendl_fd.c.o
.PHONY : ft_putendl_fd.o

# target to build an object file
ft_putendl_fd.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_putendl_fd.c.o
.PHONY : ft_putendl_fd.c.o

ft_putendl_fd.i: ft_putendl_fd.c.i
.PHONY : ft_putendl_fd.i

# target to preprocess a source file
ft_putendl_fd.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_putendl_fd.c.i
.PHONY : ft_putendl_fd.c.i

ft_putendl_fd.s: ft_putendl_fd.c.s
.PHONY : ft_putendl_fd.s

# target to generate assembly for a file
ft_putendl_fd.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_putendl_fd.c.s
.PHONY : ft_putendl_fd.c.s

ft_putnbr_fd.o: ft_putnbr_fd.c.o
.PHONY : ft_putnbr_fd.o

# target to build an object file
ft_putnbr_fd.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_putnbr_fd.c.o
.PHONY : ft_putnbr_fd.c.o

ft_putnbr_fd.i: ft_putnbr_fd.c.i
.PHONY : ft_putnbr_fd.i

# target to preprocess a source file
ft_putnbr_fd.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_putnbr_fd.c.i
.PHONY : ft_putnbr_fd.c.i

ft_putnbr_fd.s: ft_putnbr_fd.c.s
.PHONY : ft_putnbr_fd.s

# target to generate assembly for a file
ft_putnbr_fd.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_putnbr_fd.c.s
.PHONY : ft_putnbr_fd.c.s

ft_putstr_fd.o: ft_putstr_fd.c.o
.PHONY : ft_putstr_fd.o

# target to build an object file
ft_putstr_fd.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_putstr_fd.c.o
.PHONY : ft_putstr_fd.c.o

ft_putstr_fd.i: ft_putstr_fd.c.i
.PHONY : ft_putstr_fd.i

# target to preprocess a source file
ft_putstr_fd.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_putstr_fd.c.i
.PHONY : ft_putstr_fd.c.i

ft_putstr_fd.s: ft_putstr_fd.c.s
.PHONY : ft_putstr_fd.s

# target to generate assembly for a file
ft_putstr_fd.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_putstr_fd.c.s
.PHONY : ft_putstr_fd.c.s

ft_strchr.o: ft_strchr.c.o
.PHONY : ft_strchr.o

# target to build an object file
ft_strchr.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_strchr.c.o
.PHONY : ft_strchr.c.o

ft_strchr.i: ft_strchr.c.i
.PHONY : ft_strchr.i

# target to preprocess a source file
ft_strchr.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_strchr.c.i
.PHONY : ft_strchr.c.i

ft_strchr.s: ft_strchr.c.s
.PHONY : ft_strchr.s

# target to generate assembly for a file
ft_strchr.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_strchr.c.s
.PHONY : ft_strchr.c.s

ft_striteri.o: ft_striteri.c.o
.PHONY : ft_striteri.o

# target to build an object file
ft_striteri.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_striteri.c.o
.PHONY : ft_striteri.c.o

ft_striteri.i: ft_striteri.c.i
.PHONY : ft_striteri.i

# target to preprocess a source file
ft_striteri.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_striteri.c.i
.PHONY : ft_striteri.c.i

ft_striteri.s: ft_striteri.c.s
.PHONY : ft_striteri.s

# target to generate assembly for a file
ft_striteri.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_striteri.c.s
.PHONY : ft_striteri.c.s

ft_strlcat.o: ft_strlcat.c.o
.PHONY : ft_strlcat.o

# target to build an object file
ft_strlcat.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_strlcat.c.o
.PHONY : ft_strlcat.c.o

ft_strlcat.i: ft_strlcat.c.i
.PHONY : ft_strlcat.i

# target to preprocess a source file
ft_strlcat.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_strlcat.c.i
.PHONY : ft_strlcat.c.i

ft_strlcat.s: ft_strlcat.c.s
.PHONY : ft_strlcat.s

# target to generate assembly for a file
ft_strlcat.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_strlcat.c.s
.PHONY : ft_strlcat.c.s

ft_strlcpy.o: ft_strlcpy.c.o
.PHONY : ft_strlcpy.o

# target to build an object file
ft_strlcpy.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_strlcpy.c.o
.PHONY : ft_strlcpy.c.o

ft_strlcpy.i: ft_strlcpy.c.i
.PHONY : ft_strlcpy.i

# target to preprocess a source file
ft_strlcpy.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_strlcpy.c.i
.PHONY : ft_strlcpy.c.i

ft_strlcpy.s: ft_strlcpy.c.s
.PHONY : ft_strlcpy.s

# target to generate assembly for a file
ft_strlcpy.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_strlcpy.c.s
.PHONY : ft_strlcpy.c.s

ft_strlen.o: ft_strlen.c.o
.PHONY : ft_strlen.o

# target to build an object file
ft_strlen.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_strlen.c.o
.PHONY : ft_strlen.c.o

ft_strlen.i: ft_strlen.c.i
.PHONY : ft_strlen.i

# target to preprocess a source file
ft_strlen.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_strlen.c.i
.PHONY : ft_strlen.c.i

ft_strlen.s: ft_strlen.c.s
.PHONY : ft_strlen.s

# target to generate assembly for a file
ft_strlen.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_strlen.c.s
.PHONY : ft_strlen.c.s

ft_strncmp.o: ft_strncmp.c.o
.PHONY : ft_strncmp.o

# target to build an object file
ft_strncmp.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_strncmp.c.o
.PHONY : ft_strncmp.c.o

ft_strncmp.i: ft_strncmp.c.i
.PHONY : ft_strncmp.i

# target to preprocess a source file
ft_strncmp.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_strncmp.c.i
.PHONY : ft_strncmp.c.i

ft_strncmp.s: ft_strncmp.c.s
.PHONY : ft_strncmp.s

# target to generate assembly for a file
ft_strncmp.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_strncmp.c.s
.PHONY : ft_strncmp.c.s

ft_strnstr.o: ft_strnstr.c.o
.PHONY : ft_strnstr.o

# target to build an object file
ft_strnstr.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_strnstr.c.o
.PHONY : ft_strnstr.c.o

ft_strnstr.i: ft_strnstr.c.i
.PHONY : ft_strnstr.i

# target to preprocess a source file
ft_strnstr.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_strnstr.c.i
.PHONY : ft_strnstr.c.i

ft_strnstr.s: ft_strnstr.c.s
.PHONY : ft_strnstr.s

# target to generate assembly for a file
ft_strnstr.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_strnstr.c.s
.PHONY : ft_strnstr.c.s

ft_strrchr.o: ft_strrchr.c.o
.PHONY : ft_strrchr.o

# target to build an object file
ft_strrchr.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_strrchr.c.o
.PHONY : ft_strrchr.c.o

ft_strrchr.i: ft_strrchr.c.i
.PHONY : ft_strrchr.i

# target to preprocess a source file
ft_strrchr.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_strrchr.c.i
.PHONY : ft_strrchr.c.i

ft_strrchr.s: ft_strrchr.c.s
.PHONY : ft_strrchr.s

# target to generate assembly for a file
ft_strrchr.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_strrchr.c.s
.PHONY : ft_strrchr.c.s

ft_tolower.o: ft_tolower.c.o
.PHONY : ft_tolower.o

# target to build an object file
ft_tolower.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_tolower.c.o
.PHONY : ft_tolower.c.o

ft_tolower.i: ft_tolower.c.i
.PHONY : ft_tolower.i

# target to preprocess a source file
ft_tolower.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_tolower.c.i
.PHONY : ft_tolower.c.i

ft_tolower.s: ft_tolower.c.s
.PHONY : ft_tolower.s

# target to generate assembly for a file
ft_tolower.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_tolower.c.s
.PHONY : ft_tolower.c.s

ft_toupper.o: ft_toupper.c.o
.PHONY : ft_toupper.o

# target to build an object file
ft_toupper.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_toupper.c.o
.PHONY : ft_toupper.c.o

ft_toupper.i: ft_toupper.c.i
.PHONY : ft_toupper.i

# target to preprocess a source file
ft_toupper.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_toupper.c.i
.PHONY : ft_toupper.c.i

ft_toupper.s: ft_toupper.c.s
.PHONY : ft_toupper.s

# target to generate assembly for a file
ft_toupper.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/ft_toupper.c.s
.PHONY : ft_toupper.c.s

gc.o: gc.c.o
.PHONY : gc.o

# target to build an object file
gc.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc.c.o
.PHONY : gc.c.o

gc.i: gc.c.i
.PHONY : gc.i

# target to preprocess a source file
gc.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc.c.i
.PHONY : gc.c.i

gc.s: gc.c.s
.PHONY : gc.s

# target to generate assembly for a file
gc.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc.c.s
.PHONY : gc.c.s

gc2.o: gc2.c.o
.PHONY : gc2.o

# target to build an object file
gc2.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc2.c.o
.PHONY : gc2.c.o

gc2.i: gc2.c.i
.PHONY : gc2.i

# target to preprocess a source file
gc2.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc2.c.i
.PHONY : gc2.c.i

gc2.s: gc2.c.s
.PHONY : gc2.s

# target to generate assembly for a file
gc2.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc2.c.s
.PHONY : gc2.c.s

gc_itoa.o: gc_itoa.c.o
.PHONY : gc_itoa.o

# target to build an object file
gc_itoa.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc_itoa.c.o
.PHONY : gc_itoa.c.o

gc_itoa.i: gc_itoa.c.i
.PHONY : gc_itoa.i

# target to preprocess a source file
gc_itoa.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc_itoa.c.i
.PHONY : gc_itoa.c.i

gc_itoa.s: gc_itoa.c.s
.PHONY : gc_itoa.s

# target to generate assembly for a file
gc_itoa.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc_itoa.c.s
.PHONY : gc_itoa.c.s

gc_split.o: gc_split.c.o
.PHONY : gc_split.o

# target to build an object file
gc_split.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc_split.c.o
.PHONY : gc_split.c.o

gc_split.i: gc_split.c.i
.PHONY : gc_split.i

# target to preprocess a source file
gc_split.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc_split.c.i
.PHONY : gc_split.c.i

gc_split.s: gc_split.c.s
.PHONY : gc_split.s

# target to generate assembly for a file
gc_split.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc_split.c.s
.PHONY : gc_split.c.s

gc_strdup.o: gc_strdup.c.o
.PHONY : gc_strdup.o

# target to build an object file
gc_strdup.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc_strdup.c.o
.PHONY : gc_strdup.c.o

gc_strdup.i: gc_strdup.c.i
.PHONY : gc_strdup.i

# target to preprocess a source file
gc_strdup.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc_strdup.c.i
.PHONY : gc_strdup.c.i

gc_strdup.s: gc_strdup.c.s
.PHONY : gc_strdup.s

# target to generate assembly for a file
gc_strdup.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc_strdup.c.s
.PHONY : gc_strdup.c.s

gc_strjoin.o: gc_strjoin.c.o
.PHONY : gc_strjoin.o

# target to build an object file
gc_strjoin.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc_strjoin.c.o
.PHONY : gc_strjoin.c.o

gc_strjoin.i: gc_strjoin.c.i
.PHONY : gc_strjoin.i

# target to preprocess a source file
gc_strjoin.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc_strjoin.c.i
.PHONY : gc_strjoin.c.i

gc_strjoin.s: gc_strjoin.c.s
.PHONY : gc_strjoin.s

# target to generate assembly for a file
gc_strjoin.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc_strjoin.c.s
.PHONY : gc_strjoin.c.s

gc_strmapi.o: gc_strmapi.c.o
.PHONY : gc_strmapi.o

# target to build an object file
gc_strmapi.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc_strmapi.c.o
.PHONY : gc_strmapi.c.o

gc_strmapi.i: gc_strmapi.c.i
.PHONY : gc_strmapi.i

# target to preprocess a source file
gc_strmapi.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc_strmapi.c.i
.PHONY : gc_strmapi.c.i

gc_strmapi.s: gc_strmapi.c.s
.PHONY : gc_strmapi.s

# target to generate assembly for a file
gc_strmapi.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc_strmapi.c.s
.PHONY : gc_strmapi.c.s

gc_strtrim.o: gc_strtrim.c.o
.PHONY : gc_strtrim.o

# target to build an object file
gc_strtrim.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc_strtrim.c.o
.PHONY : gc_strtrim.c.o

gc_strtrim.i: gc_strtrim.c.i
.PHONY : gc_strtrim.i

# target to preprocess a source file
gc_strtrim.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc_strtrim.c.i
.PHONY : gc_strtrim.c.i

gc_strtrim.s: gc_strtrim.c.s
.PHONY : gc_strtrim.s

# target to generate assembly for a file
gc_strtrim.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc_strtrim.c.s
.PHONY : gc_strtrim.c.s

gc_substr.o: gc_substr.c.o
.PHONY : gc_substr.o

# target to build an object file
gc_substr.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc_substr.c.o
.PHONY : gc_substr.c.o

gc_substr.i: gc_substr.c.i
.PHONY : gc_substr.i

# target to preprocess a source file
gc_substr.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc_substr.c.i
.PHONY : gc_substr.c.i

gc_substr.s: gc_substr.c.s
.PHONY : gc_substr.s

# target to generate assembly for a file
gc_substr.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/gc_substr.c.s
.PHONY : gc_substr.c.s

get_next_line/get_next_line.o: get_next_line/get_next_line.c.o
.PHONY : get_next_line/get_next_line.o

# target to build an object file
get_next_line/get_next_line.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/get_next_line/get_next_line.c.o
.PHONY : get_next_line/get_next_line.c.o

get_next_line/get_next_line.i: get_next_line/get_next_line.c.i
.PHONY : get_next_line/get_next_line.i

# target to preprocess a source file
get_next_line/get_next_line.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/get_next_line/get_next_line.c.i
.PHONY : get_next_line/get_next_line.c.i

get_next_line/get_next_line.s: get_next_line/get_next_line.c.s
.PHONY : get_next_line/get_next_line.s

# target to generate assembly for a file
get_next_line/get_next_line.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/get_next_line/get_next_line.c.s
.PHONY : get_next_line/get_next_line.c.s

get_next_line/get_next_line_utils.o: get_next_line/get_next_line_utils.c.o
.PHONY : get_next_line/get_next_line_utils.o

# target to build an object file
get_next_line/get_next_line_utils.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/get_next_line/get_next_line_utils.c.o
.PHONY : get_next_line/get_next_line_utils.c.o

get_next_line/get_next_line_utils.i: get_next_line/get_next_line_utils.c.i
.PHONY : get_next_line/get_next_line_utils.i

# target to preprocess a source file
get_next_line/get_next_line_utils.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/get_next_line/get_next_line_utils.c.i
.PHONY : get_next_line/get_next_line_utils.c.i

get_next_line/get_next_line_utils.s: get_next_line/get_next_line_utils.c.s
.PHONY : get_next_line/get_next_line_utils.s

# target to generate assembly for a file
get_next_line/get_next_line_utils.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/get_next_line/get_next_line_utils.c.s
.PHONY : get_next_line/get_next_line_utils.c.s

stack.o: stack.c.o
.PHONY : stack.o

# target to build an object file
stack.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/stack.c.o
.PHONY : stack.c.o

stack.i: stack.c.i
.PHONY : stack.i

# target to preprocess a source file
stack.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/stack.c.i
.PHONY : stack.c.i

stack.s: stack.c.s
.PHONY : stack.s

# target to generate assembly for a file
stack.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/stack.c.s
.PHONY : stack.c.s

stack2.o: stack2.c.o
.PHONY : stack2.o

# target to build an object file
stack2.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/stack2.c.o
.PHONY : stack2.c.o

stack2.i: stack2.c.i
.PHONY : stack2.i

# target to preprocess a source file
stack2.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/stack2.c.i
.PHONY : stack2.c.i

stack2.s: stack2.c.s
.PHONY : stack2.s

# target to generate assembly for a file
stack2.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/stack2.c.s
.PHONY : stack2.c.s

stack3.o: stack3.c.o
.PHONY : stack3.o

# target to build an object file
stack3.c.o:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/stack3.c.o
.PHONY : stack3.c.o

stack3.i: stack3.c.i
.PHONY : stack3.i

# target to preprocess a source file
stack3.c.i:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/stack3.c.i
.PHONY : stack3.c.i

stack3.s: stack3.c.s
.PHONY : stack3.s

# target to generate assembly for a file
stack3.c.s:
	cd /Users/ijaehyeon/source/42_printf && $(MAKE) $(MAKESILENT) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/stack3.c.s
.PHONY : stack3.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... libft"
	@echo "... ft_atoi.o"
	@echo "... ft_atoi.i"
	@echo "... ft_atoi.s"
	@echo "... ft_bzero.o"
	@echo "... ft_bzero.i"
	@echo "... ft_bzero.s"
	@echo "... ft_calloc.o"
	@echo "... ft_calloc.i"
	@echo "... ft_calloc.s"
	@echo "... ft_isalnum.o"
	@echo "... ft_isalnum.i"
	@echo "... ft_isalnum.s"
	@echo "... ft_isalpha.o"
	@echo "... ft_isalpha.i"
	@echo "... ft_isalpha.s"
	@echo "... ft_isascii.o"
	@echo "... ft_isascii.i"
	@echo "... ft_isascii.s"
	@echo "... ft_isdigit.o"
	@echo "... ft_isdigit.i"
	@echo "... ft_isdigit.s"
	@echo "... ft_isprint.o"
	@echo "... ft_isprint.i"
	@echo "... ft_isprint.s"
	@echo "... ft_lstadd_back.o"
	@echo "... ft_lstadd_back.i"
	@echo "... ft_lstadd_back.s"
	@echo "... ft_lstadd_front.o"
	@echo "... ft_lstadd_front.i"
	@echo "... ft_lstadd_front.s"
	@echo "... ft_lstclear.o"
	@echo "... ft_lstclear.i"
	@echo "... ft_lstclear.s"
	@echo "... ft_lstdelone.o"
	@echo "... ft_lstdelone.i"
	@echo "... ft_lstdelone.s"
	@echo "... ft_lstiter.o"
	@echo "... ft_lstiter.i"
	@echo "... ft_lstiter.s"
	@echo "... ft_lstlast.o"
	@echo "... ft_lstlast.i"
	@echo "... ft_lstlast.s"
	@echo "... ft_lstmap.o"
	@echo "... ft_lstmap.i"
	@echo "... ft_lstmap.s"
	@echo "... ft_lstnew.o"
	@echo "... ft_lstnew.i"
	@echo "... ft_lstnew.s"
	@echo "... ft_lstsize.o"
	@echo "... ft_lstsize.i"
	@echo "... ft_lstsize.s"
	@echo "... ft_memchr.o"
	@echo "... ft_memchr.i"
	@echo "... ft_memchr.s"
	@echo "... ft_memcmp.o"
	@echo "... ft_memcmp.i"
	@echo "... ft_memcmp.s"
	@echo "... ft_memcpy.o"
	@echo "... ft_memcpy.i"
	@echo "... ft_memcpy.s"
	@echo "... ft_memmove.o"
	@echo "... ft_memmove.i"
	@echo "... ft_memmove.s"
	@echo "... ft_memset.o"
	@echo "... ft_memset.i"
	@echo "... ft_memset.s"
	@echo "... ft_putchar_fd.o"
	@echo "... ft_putchar_fd.i"
	@echo "... ft_putchar_fd.s"
	@echo "... ft_putendl_fd.o"
	@echo "... ft_putendl_fd.i"
	@echo "... ft_putendl_fd.s"
	@echo "... ft_putnbr_fd.o"
	@echo "... ft_putnbr_fd.i"
	@echo "... ft_putnbr_fd.s"
	@echo "... ft_putstr_fd.o"
	@echo "... ft_putstr_fd.i"
	@echo "... ft_putstr_fd.s"
	@echo "... ft_strchr.o"
	@echo "... ft_strchr.i"
	@echo "... ft_strchr.s"
	@echo "... ft_striteri.o"
	@echo "... ft_striteri.i"
	@echo "... ft_striteri.s"
	@echo "... ft_strlcat.o"
	@echo "... ft_strlcat.i"
	@echo "... ft_strlcat.s"
	@echo "... ft_strlcpy.o"
	@echo "... ft_strlcpy.i"
	@echo "... ft_strlcpy.s"
	@echo "... ft_strlen.o"
	@echo "... ft_strlen.i"
	@echo "... ft_strlen.s"
	@echo "... ft_strncmp.o"
	@echo "... ft_strncmp.i"
	@echo "... ft_strncmp.s"
	@echo "... ft_strnstr.o"
	@echo "... ft_strnstr.i"
	@echo "... ft_strnstr.s"
	@echo "... ft_strrchr.o"
	@echo "... ft_strrchr.i"
	@echo "... ft_strrchr.s"
	@echo "... ft_tolower.o"
	@echo "... ft_tolower.i"
	@echo "... ft_tolower.s"
	@echo "... ft_toupper.o"
	@echo "... ft_toupper.i"
	@echo "... ft_toupper.s"
	@echo "... gc.o"
	@echo "... gc.i"
	@echo "... gc.s"
	@echo "... gc2.o"
	@echo "... gc2.i"
	@echo "... gc2.s"
	@echo "... gc_itoa.o"
	@echo "... gc_itoa.i"
	@echo "... gc_itoa.s"
	@echo "... gc_split.o"
	@echo "... gc_split.i"
	@echo "... gc_split.s"
	@echo "... gc_strdup.o"
	@echo "... gc_strdup.i"
	@echo "... gc_strdup.s"
	@echo "... gc_strjoin.o"
	@echo "... gc_strjoin.i"
	@echo "... gc_strjoin.s"
	@echo "... gc_strmapi.o"
	@echo "... gc_strmapi.i"
	@echo "... gc_strmapi.s"
	@echo "... gc_strtrim.o"
	@echo "... gc_strtrim.i"
	@echo "... gc_strtrim.s"
	@echo "... gc_substr.o"
	@echo "... gc_substr.i"
	@echo "... gc_substr.s"
	@echo "... get_next_line/get_next_line.o"
	@echo "... get_next_line/get_next_line.i"
	@echo "... get_next_line/get_next_line.s"
	@echo "... get_next_line/get_next_line_utils.o"
	@echo "... get_next_line/get_next_line_utils.i"
	@echo "... get_next_line/get_next_line_utils.s"
	@echo "... stack.o"
	@echo "... stack.i"
	@echo "... stack.s"
	@echo "... stack2.o"
	@echo "... stack2.i"
	@echo "... stack2.s"
	@echo "... stack3.o"
	@echo "... stack3.i"
	@echo "... stack3.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /Users/ijaehyeon/source/42_printf && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

